[package]
name = "iced-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
blurhash.workspace = true
bytemuck = { version = "1", features = ["derive"] }
chrono.workspace = true
chrono-tz.workspace = true
const_format.workspace = true
deplace_core = { workspace = true, features = ["iced_desktop"] }
dirs.workspace = true
iced.workspace = true
iced_video_player.workspace = true
image.workspace = true
indexmap.workspace = true
lru.workspace = true
macros.workspace = true
matrix-sdk.workspace = true
matrix-sdk-ui.workspace = true
phosphor-svgs.workspace = true
serde_json.workspace = true
sweeten.workspace = true
thumbhash.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
url-macro.workspace = true
uuid.workspace = true
interprocess = "2.4.4"

[dev-dependencies]
naga = "27"

[lints.clippy]
exit = "warn"
let_underscore_must_use = "warn"
panic_in_result_fn = "warn"
string_slice = "warn"
todo = "warn"
unchecked_time_subtraction = "warn"
unimplemented = "warn"
unreachable = "warn"
unwrap_used = "warn"
