[workspace]
resolver = "2"
members = [
  "deplace_core",
  "desktop",
]

default-members = ["desktop"]

[workspace.dependencies]
deplace_core = { path = "deplace_core" }

anyhow = "1"
getrandom = "0.4.3"
interprocess = { version = "2", features = ["tokio"] }
matrix-sdk = {
  version = "0.18.0",
  features = [
    "anyhow",
    "e2e-encryption",
    "experimental-element-recent-emojis",
    "experimental-search",
    "experimental-send-custom-to-device",
    "sqlite",
  ]
}
matrix-sdk-ui = "0.18.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
