[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/desktop",
]

default-members = ["crates/desktop"]

[workspace.dependencies]
core = { path = "crates/core" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
interprocess = { version = "2", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
gpui = "0.2"
anyhow = "1"
