[workspace]
resolver = "2"
members = [
  "deplace_core",
  "iced-desktop",
  "macros",
]

default-members = ["iced-desktop"]

[workspace.dependencies]
deplace_core = { path = "deplace_core" }
macros = { path = "macros" }

anyhow = "1"
base64 = "0.23.0"
blurhash = "0.2.3"
chrono = "0.4.45"
chrono-tz = { version = "0.10.4", features = ["serde"] }
const_format = "0.2.36"
csscolorparser = "0.8.3"
dashmap = "7.0.0-rc2"
dirs = "6.0.0"
enumset = { version = "1.1.14", features = ["serde"] }
futures = "0.3.34"
futures-util = "0.3"
getrandom = { version = "0.4.0-rc.1" }
iced = {
  git = "https://github.com/acisama/iced",
  version = "0.15.0-dev",
  features = [
    "advanced",
    "canvas",
    "debug",
    "image",
    "svg",
    "time-travel",
    "tokio",
  ]
}
iced_video_player = { git = "https://codeberg.org/aosiuejhf/iced_video_player.git" }
image = "0.25.10"
imbl = "6.1.0"
indexmap = "2.14.2"
infer = "0.22.0"
interprocess = { version = "2", features = ["tokio"] }
keyboard-types = { version = "0.8.3", features = ["serde"] }
livekit = "0.9.4"
lru = "0.18.2"
matrix-sdk = { version = "0.19.1", features = ["anyhow", "bundled-sqlite", "e2e-encryption", "experimental-element-recent-emojis", "experimental-search", "experimental-send-custom-to-device", "sso-login"] }
matrix-sdk-ui = "0.19.1"
mime = "0.3.17"
mime_guess = "2.0.5"
nucleo = "0.5.0"
open = "5.4.4"
phosphor-svgs = "0.3.0"
rayon = "1.12.0"
reqwest = { version = "0.13.5", default-features = false, features = ["json"] }
ruma = { version = "0.17.0", features = ["unstable-msc4095"] }
ruma-html = { version = "0.9.0", features = ["matrix"] }
rust-embed = "8.12.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11.0"
smallvec = "1.15.2"
sweeten = { git = "https://codeberg.org/aosiuejhf/sweeten-fork.git", branch = "master" }
thumbhash = "0.1.0"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.19"
toml_edit = { version = "0.25.13", features = ["serde"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"
url-macro = "0.2.4"
uuid = { version = "1.24.0", features = ["v7"] }

# [patch."https://codeberg.org/aosiuejhf/iced_video_player.git"]
# iced_video_player = { path = "/home/eriko/iced_video_player" }

# [patch."https://codeberg.org/aosiuejhf/sweeten-fork.git"]
# sweeten = { path = "/home/eriko/sweeten-fork" }

# [patch."https://github.com/acisama/iced"]
# iced = { path = "/home/eriko/iced" }
# iced_core = { path = "../iced/core" }
# iced_graphics = { path = "../iced/graphics" }
# iced_wgpu = { path = "../iced/wgpu" }
