[package]
name = "deplace_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
base64.workspace = true
blurhash.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
const_format.workspace = true
csscolorparser.workspace = true
dashmap.workspace = true
dirs.workspace = true
ego-tree = "0.11.0"
enumset.workspace = true
futures = "0.3.33"
futures-util.workspace = true
getrandom.workspace = true
gpui = { workspace = true, optional = true }
hex = "0.4.3"
iced = { workspace = true, optional = true }
image.workspace = true
imbl.workspace = true
keyring-core = "1.0.0"
macros.workspace = true
# livekit.workspace = true
matrix-sdk.workspace = true
matrix-sdk-ui.workspace = true
mime_guess.workspace = true
reqwest.workspace = true
ruma.workspace = true
scraper = "0.27.0"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml_edit.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android-native-keyring-store = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
zbus-secret-service-keyring-store = { version = "1.0", features = ["rt-async-io-crypto-rust"] }

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "1.0", features = ["keychain"] }

[target."cfg(windows)".dependencies]
windows-native-keyring-store = "1.0"

[features]
desktop = ["gpui"]
iced_desktop = ["iced"]

[lints.clippy]
exit = "warn"
let_underscore_must_use = "warn"
panic_in_result_fn = "warn"
string_slice = "warn"
todo = "warn"
unchecked_time_subtraction = "warn"
unimplemented = "warn"
unreachable = "warn"
unwrap_used = "warn"
